project:
  type: website

website:
  title: "Data Science Portfolio"
  navbar:
    left: 
      - text: Home
        href: index.qmd
      - text: R
        href: r_projects.qmd
      - text: Python
        href: python_projects.qmd
      - text: SQL
        href: sql_projects.qmd
      - text: Resume
        href: resume.qmd
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/edwardbquinn/
      - icon: github
        href: https://github.com/edward-quinn
      - icon: mortarboard-fill
        href: https://scholar.google.com/citations?hl=en&user=sL13dZIAAAAJ&view_op=list_works&sortby=pubdate
format:
  html:
    theme: minty
    css: styles.css

editor: source

