project:
  type: website

website:
  title: "Data Science Portfolio"
  favicon: Edward Quinn-min.jpg
  navbar:
    left: 
      - text: Home
        href: index.qmd
      - text: Machine Learning
        href: machine_learning.qmd
      - text: Data Visualization
        href: data_visualization.qmd
      - text: Database Management
        href: database_management.qmd
      - text: Resume
        href: resume.qmd
format:
  html:
    theme: minty
    css: styles.css
    code-link: true
    code-fold: show
    highlight-style: breeze

editor: source

