project:
  type: website

website:
  title: "Data Science Portfolio"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/edwardbquinn/
      - icon: github
        href: https://github.com/edward-quinn
      - icon: mortarboard-fill
        href: https://scholar.google.com/citations?hl=en&user=sL13dZIAAAAJ&view_op=list_works&sortby=pubdate
format:
  html:
    theme: minty
    css: styles.css

editor: visual

