project:
  type: website

website:
  title: "Edward B. Quinn, PhD, MPH"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - icon: google scholar
format:
  html:
    theme: minty
    css: styles.css

editor: visual

