project:
  type: website

website:
  title: "data_science_portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - icon: google scholar
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

